import dash
from dash import dcc, html
from dash.dependencies import Input, Output, State
import pandas as pd
import plotly.express as px
from tensorflow.keras.models import load_model
import joblib

# Cargar encoders previamente guardados
encoders = joblib.load("encoders.pkl")
# Cargar modelo entrenado
model = load_model("best_model.h5")

# Cargar datos para gráficas
df = pd.read_csv("Resultados__nicos_Saber_11_20250512.csv")


colores_amarillos = [
    "#FFF8E1",
    "#FFECB3",
    "#FFE082",
    "#FFD54F",
    "#FFCA28",
    "#FFC107",
    "#FFB300",
    "#FFA000",
    "#FF8F00",
    "#FF6F00",
]

# Opciones para el primer gráfico
opciones_educacion = [
    {"label": "Educación de la Madre", "value": "FAMI_EDUCACIONMADRE"},
    {"label": "Educación del Padre", "value": "FAMI_EDUCACIONPADRE"},
]

# Opciones para dropdowns de predicción
opciones = {
    "COLE_AREA_UBICACION": ["RURAL", "URBANO"],
    "COLE_BILINGUE": ["S", "N"],
    "COLE_CARACTER": ["ACADÉMICO", "TÉCNICO", "TÉCNICO/ACADÉMICO", "OTRO"],
    "COLE_GENERO": ["MIXTO", "FEMENINO", "MASCULINO"],
    "COLE_NATURALEZA": ["OFICIAL", "NO OFICIAL"],
    "COLE_SEDE_PRINCIPAL": ["S", "N"],
    "ESTU_GENERO": ["M", "F"],
    "FAMI_EDUCACIONMADRE": [
        "EducaciÃ³n profesional completa",
        "EducaciÃ³n profesional incompleta",
        "Ninguno",
        "No sabe",
        "Postgrado",
        "Primaria completa",
        "Primaria incompleta",
        "Secundaria (Bachillerato) completa",
        "Secundaria (Bachillerato) incompleta",
        "TÃ©cnica o tecnolÃ³gica completa",
        "TÃ©cnica o tecnolÃ³gica incompleta",
    ],
    "FAMI_EDUCACIONPADRE": [
        "EducaciÃ³n profesional completa",
        "EducaciÃ³n profesional incompleta",
        "Ninguno",
        "No sabe",
        "Postgrado",
        "Primaria completa",
        "Primaria incompleta",
        "Secundaria (Bachillerato) completa",
        "Secundaria (Bachillerato) incompleta",
        "TÃ©cnica o tecnolÃ³gica completa",
        "TÃ©cnica o tecnolÃ³gica incompleta",
    ],
    "FAMI_ESTRATOVIVIENDA": [
        "Estrato 1",
        "Estrato 2",
        "Estrato 3",
        "Estrato 4",
        "Estrato 5",
        "Estrato 6",
    ],
    "FAMI_TIENEAUTOMOVIL": ["Si", "No"],
    "FAMI_TIENECOMPUTADOR": ["Si", "No"],
    "COLE_MCPIO_UBICACION": [
        "ABEJORRAL",
        "ABREGO",
        "ABRIAQUI",
        "ACACIAS",
        "ACANDI",
        "ACEVEDO",
        "ACHI",
        "AGRADO",
        "AGUA DE DIOS",
        "AGUACHICA",
        "AGUADA",
        "AGUADAS",
        "AGUAZUL",
        "AGUSTIN CODAZZI",
        "AIPE",
        "ALBAN",
        "ALBAN (SAN JOSE)",
        "ALBANIA",
        "ALCALA",
        "ALDANA",
        "ALEJANDRIA",
        "ALGARROBO",
        "ALGECIRAS",
        "ALMAGUER",
        "ALMEIDA",
        "ALPUJARRA",
        "ALTAMIRA",
        "ALTO BAUDO (PIE DE PATO)",
        "ALTOS DEL ROSARIO",
        "ALVARADO",
        "AMAGA",
        "AMALFI",
        "AMBALEMA",
        "ANAPOIMA",
        "ANCUYA",
        "ANDALUCIA",
        "ANDES",
        "ANGELOPOLIS",
        "ANGOSTURA",
        "ANOLAIMA",
        "ANORI",
        "ANSERMA",
        "ANSERMANUEVO",
        "ANZA",
        "ANZOATEGUI",
        "APARTADO",
        "APIA",
        "AQUITANIA",
        "ARACATACA",
        "ARANZAZU",
        "ARATOCA",
        "ARAUCA",
        "ARAUQUITA",
        "ARBELAEZ",
        "ARBOLEDA (BERRUECOS)",
        "ARBOLEDAS",
        "ARBOLETES",
        "ARCABUCO",
        "ARENAL",
        "ARGELIA",
        "ARIGUANI (EL DIFICIL)",
        "ARJONA",
        "ARMENIA",
        "ARMERO (GUAYABAL)",
        "ARROYOHONDO",
        "ASTREA",
        "ATACO",
        "ATRATO (YUTO)",
        "AYAPEL",
        "BAGADO",
        "BAHIA SOLANO (MUTIS)",
        "BAJO BAUDO (PIZARRO)",
        "BALBOA",
        "BARANOA",
        "BARAYA",
        "BARBACOAS",
        "BARBOSA",
        "BARICHARA",
        "BARRANCA DE UPIA",
        "BARRANCABERMEJA",
        "BARRANCAS",
        "BARRANCO DE LOBA",
        "BARRANCO MINAS",
        "BARRANQUILLA",
        "BECERRIL",
        "BELALCAZAR",
        "BELEN",
        "BELEN DE BAJIRA",
        "BELEN DE LOS ANDAQUIES",
        "BELEN DE UMBRIA",
        "BELLO",
        "BELMIRA",
        "BELTRAN",
        "BERBEO",
        "BETANIA",
        "BETEITIVA",
        "BETULIA",
        "BITUIMA",
        "BOAVITA",
        "BOCHALEMA",
        "BOGOTÃ\x81 D.C.",
        "BOJACÃ\x81",
        "BOJAYA (BELLAVISTA)",
        "BOLIVAR",
        "BOSCONIA",
        "BOYACA",
        "BRICEÃ\x91O",
        "BUCARAMANGA",
        "BUCARASICA",
        "BUENAVENTURA",
        "BUENAVISTA",
        "BUENOS AIRES",
        "BUESACO",
        "BUGA",
        "BUGALAGRANDE",
        "BURITICA",
        "CABRERA",
        "CABUYARO",
        "CACERES",
        "CACHIPAY",
        "CACHIRA",
        "CACOTA",
        "CAICEDO",
        "CAICEDONIA",
        "CAIMITO",
        "CAJAMARCA",
        "CAJIBIO",
        "CAJICA",
        "CALAMAR",
        "CALARCA",
        "CALDAS",
        "CALDONO",
        "CALI",
        "CALIFORNIA",
        "CALIMA (DARIEN)",
        "CALOTO",
        "CAMPAMENTO",
        "CAMPO DE LA CRUZ",
        "CAMPOALEGRE",
        "CAMPOHERMOSO",
        "CANALETE",
        "CANDELARIA",
        "CANTAGALLO",
        "CANTON DEL SAN PABLO",
        "CAPARRAPI",
        "CAPITANEJO",
        "CAQUEZA",
        "CARACOLI",
        "CARAMANTA",
        "CARCASI",
        "CAREPA",
        "CARMEN DE APICALA",
        "CARMEN DE CARUPA",
        "CARMEN DE VIBORAL",
        "CARMEN DEL DARIEN",
        "CAROLINA",
        "CARTAGENA",
        "CARTAGENA DEL CHAIRA",
        "CARTAGO",
        "CASABIANCA",
        "CASTILLA LA NUEVA",
        "CAUCASIA",
        "CAÃ\x91ASGORDAS",
        "CEPITA",
        "CERETE",
        "CERINZA",
        "CERRITO",
        "CERRO SAN ANTONIO",
        "CERTEGUI",
        "CHACHAGUI",
        "CHAGUANI",
        "CHALAN",
        "CHAMEZA",
        "CHAPARRAL",
        "CHARALA",
        "CHARTA",
        "CHIA",
        "CHIGORODO",
        "CHIMA",
        "CHIMICHAGUA",
        "CHINACOTA",
        "CHINAVITA",
        "CHINCHINA",
        "CHINU",
        "CHIPAQUE",
        "CHIPATA",
        "CHIQUINQUIRA",
        "CHIQUIZA",
        "CHIRIGUANA",
        "CHISCAS",
        "CHITA",
        "CHITAGA",
        "CHITARAQUE",
        "CHIVATA",
        "CHIVOLO",
        "CHIVOR",
        "CHOACHI",
        "CHOCONTA",
        "CICUCO",
        "CIENAGA",
        "CIENAGA DE ORO",
        "CIENEGA",
        "CIMITARRA",
        "CIRCASIA",
        "CISNEROS",
        "CLEMENCIA",
        "COCORNA",
        "COELLO",
        "COGUA",
        "COLOMBIA",
        "COLON",
        "COLON (GENOVA)",
        "COLOSO (RICAURTE)",
        "COMBITA",
        "CONCEPCION",
        "CONCORDIA",
        "CONDOTO",
        "CONFINES",
        "CONSACA",
        "CONTADERO",
        "CONTRATACION",
        "CONVENCION",
        "COPACABANA",
        "COPER",
        "CORDOBA",
        "CORINTO",
        "COROMORO",
        "COROZAL",
        "CORRALES",
        "COTA",
        "COTORRA",
        "COVARACHIA",
        "COVEÃ\x91AS",
        "COYAIMA",
        "CRAVO NORTE",
        "CUASPUD (CARLOSAMA)",
        "CUBARA",
        "CUBARRAL",
        "CUCAITA",
        "CUCUNUBA",
        "CUCUTA",
        "CUCUTILLA",
        "CUITIVA",
        "CUMARAL",
        "CUMARIBO",
        "CUMBAL",
        "CUMBITARA",
        "CUNDAY",
        "CURILLO",
        "CURITI",
        "CURUMANI",
        "DABEIBA",
        "DAGUA",
        "DIBULLA",
        "DISTRACCION",
        "DOLORES",
        "DON MATIAS",
        "DOS QUEBRADAS",
        "DUITAMA",
        "DURANIA",
        "EBEJICO",
        "EL AGUILA",
        "EL BAGRE",
        "EL BANCO",
        "EL CAIRO",
        "EL CALVARIO",
        "EL CARMEN",
        "EL CARMEN DE BOLIVAR",
        "EL CASTILLO",
        "EL CERRITO",
        "EL CHARCO",
        "EL COCUY",
        "EL COLEGIO",
        "EL COPEY",
        "EL DONCELLO",
        "EL DORADO",
        "EL DOVIO",
        "EL ENCANTO",
        "EL ESPINO",
        "EL GUACAMAYO",
        "EL GUAMO",
        "EL LITORAL DEL SAN JUAN",
        "EL MOLINO",
        "EL PASO",
        "EL PAUJIL",
        "EL PEÃ\x91OL",
        "EL PEÃ\x91ON",
        "EL PIÃ\x91ON",
        "EL PLAYON",
        "EL RETEN",
        "EL RETORNO",
        "EL ROBLE",
        "EL ROSAL",
        "EL ROSARIO",
        "EL TABLON",
        "EL TAMBO",
        "EL TARRA",
        "EL ZULIA",
        "ELIAS",
        "ENCINO",
        "ENCISO",
        "ENTRERRIOS",
        "ENVIGADO",
        "ESPINAL",
        "FACATATIVA",
        "FALAN",
        "FILADELFIA",
        "FILANDIA",
        "FIRAVITOBA",
        "FLANDES",
        "FLORENCIA",
        "FLORESTA",
        "FLORIAN",
        "FLORIDA",
        "FLORIDABLANCA",
        "FOMEQUE",
        "FONSECA",
        "FORTUL",
        "FOSCA",
        "FRANCISCO PIZARRO",
        "FREDONIA",
        "FRESNO",
        "FRONTINO",
        "FUENTE DE ORO",
        "FUNDACION",
        "FUNES",
        "FUNZA",
        "FUQUENE",
        "FUSAGASUGA",
        "GACHALA",
        "GACHANCIPA",
        "GACHANTIVA",
        "GACHETA",
        "GALAN",
        "GALAPA",
        "GALERAS (NUEVA GRANADA)",
        "GAMA",
        "GAMARRA",
        "GAMBITA",
        "GAMEZA",
        "GARAGOA",
        "GARZON",
        "GENOVA",
        "GIGANTE",
        "GINEBRA",
        "GIRALDO",
        "GIRARDOT",
        "GIRARDOTA",
        "GIRON",
        "GOMEZ PLATA",
        "GONZALEZ",
        "GRAMALOTE",
        "GRANADA",
        "GUACA",
        "GUACAMAYAS",
        "GUACARI",
        "GUACHENÃ\x89",
        "GUACHETA",
        "GUACHUCAL",
        "GUADALUPE",
        "GUADUAS",
        "GUAITARILLA",
        "GUALMATAN",
        "GUAMAL",
        "GUAMO",
        "GUAPI",
        "GUAPOTA",
        "GUARANDA",
        "GUARNE",
        "GUASCA",
        "GUATAPE",
        "GUATAQUI",
        "GUATAVITA",
        "GUATEQUE",
        "GUATICA",
        "GUAVATA",
        "GUAYABAL DE SIQUIMA",
        "GUAYABETAL",
        "GUAYATA",
        "GUEPSA",
        "GUICAN",
        "GUTIERREZ",
        "HACARI",
        "HATILLO DE LOBA",
        "HATO",
        "HATO COROZAL",
        "HATONUEVO",
        "HELICONIA",
        "HERRAN",
        "HERVEO",
        "HISPANIA",
        "HOBO",
        "HONDA",
        "IBAGUE",
        "ICONONZO",
        "ILES",
        "IMUES",
        "INIRIDA",
        "INZA",
        "IPIALES",
        "IQUIRA",
        "ISNOS",
        "ISTMINA",
        "ITAGUI",
        "ITUANGO",
        "IZA",
        "JAMBALO",
        "JAMUNDI",
        "JARDIN",
        "JENESANO",
        "JERICO",
        "JERUSALEN",
        "JESUS MARIA",
        "JORDAN",
        "JUAN DE ACOSTA",
        "JUNIN",
        "JURADO",
        "LA APARTADA (LA FRONTERA)",
        "LA ARGENTINA",
        "LA BELLEZA",
        "LA CALERA",
        "LA CAPILLA",
        "LA CEJA",
        "LA CELIA",
        "LA CHORRERA",
        "LA CRUZ",
        "LA CUMBRE",
        "LA DORADA",
        "LA ESPERANZA",
        "LA ESTRELLA",
        "LA FLORIDA",
        "LA GLORIA",
        "LA JAGUA DE IBIRICO",
        "LA JAGUA DEL PILAR",
        "LA LLANADA",
        "LA MACARENA",
        "LA MERCED",
        "LA MESA",
        "LA MONTAÃ\x91ITA",
        "LA PALMA",
        "LA PAZ",
        "LA PAZ (ROBLES)",
        "LA PEDRERA",
        "LA PEÃ\x91A",
        "LA PINTADA",
        "LA PLATA",
        "LA PLAYA",
        "LA PRIMAVERA",
        "LA SALINA",
        "LA SIERRA",
        "LA TEBAIDA",
        "LA TOLA",
        "LA UNION",
        "LA URIBE",
        "LA UVITA",
        "LA VEGA",
        "LA VICTORIA",
        "LA VIRGINIA",
        "LABATECA",
        "LABRANZAGRANDE",
        "LANDAZURI",
        "LEBRIJA",
        "LEIVA",
        "LEJANIAS",
        "LENGUAZAQUE",
        "LERIDA",
        "LETICIA",
        "LIBANO",
        "LIBORINA",
        "LINARES",
        "LLORO",
        "LOPEZ (MICAY)",
        "LORICA",
        "LOS ANDES (SOTOMAYOR)",
        "LOS CORDOBAS",
        "LOS PALMITOS",
        "LOS PATIOS",
        "LOS SANTOS",
        "LOURDES",
        "LURUACO",
        "MACANAL",
        "MACARAVITA",
        "MACEO",
        "MACHETA",
        "MADRID",
        "MAGANGUE",
        "MAGUI (PAYAN)",
        "MAHATES",
        "MAICAO",
        "MAJAGUAL",
        "MALAGA",
        "MALAMBO",
        "MALLAMA (PIEDRANCHA)",
        "MANATI",
        "MANAURE",
        "MANAURE BALCON DEL CESAR",
        "MANI",
        "MANIZALES",
        "MANTA",
        "MANZANARES",
        "MAPIRIPAN",
        "MAPIRIPANA",
        "MARGARITA",
        "MARIA LA BAJA",
        "MARINILLA",
        "MARIPI",
        "MARIQUITA",
        "MARMATO",
        "MARQUETALIA",
        "MARSELLA",
        "MARULANDA",
        "MATANZA",
        "MEDELLIN",
        "MEDINA",
        "MEDIO ATRATO",
        "MEDIO BAUDO",
        "MEDIO SAN JUAN",
        "MELGAR",
        "MERCADERES",
        "MESETAS",
        "MILAN",
        "MIRAFLORES",
        "MIRANDA",
        "MISTRATO",
        "MITU",
        "MOCOA",
        "MOGOTES",
        "MOLAGAVITA",
        "MOMIL",
        "MOMPOS",
        "MONGUA",
        "MONGUI",
        "MONIQUIRA",
        "MONTEBELLO",
        "MONTECRISTO",
        "MONTELIBANO",
        "MONTENEGRO",
        "MONTERIA",
        "MONTERREY",
        "MORALES",
        "MORELIA",
        "MORROA",
        "MOSQUERA",
        "MOTAVITA",
        "MOÃ\x91ITOS",
        "MURILLO",
        "MURINDO",
        "MUTATA",
        "MUTISCUA",
        "MUZO",
        "NARIÃ\x91O",
        "NATAGA",
        "NATAGAIMA",
        "NECHI",
        "NECOCLI",
        "NEIRA",
        "NEIVA",
        "NEMOCON",
        "NILO",
        "NIMAIMA",
        "NOBSA",
        "NOCAIMA",
        "NORCASIA",
        "NOROSI",
        "NOVITA",
        "NUEVA GRANADA",
        "NUEVO COLON",
        "NUNCHIA",
        "NUQUI",
        "OBANDO",
        "OCAMONTE",
        "OCAÃ\x91A",
        "OIBA",
        "OICATA",
        "OLAYA",
        "OLAYA HERRERA",
        "ONZAGA",
        "OPORAPA",
        "ORITO",
        "OROCUE",
        "ORTEGA",
        "OSPINA",
        "OTANCHE",
        "OVEJAS",
        "PACHAVITA",
        "PACHO",
        "PACORA",
        "PADILLA",
        "PAEZ",
        "PAEZ (BELALCAZAR)",
        "PAICOL",
        "PAILITAS",
        "PAIME",
        "PAIPA",
        "PAJARITO",
        "PALERMO",
        "PALESTINA",
        "PALMAR",
        "PALMAR DE VARELA",
        "PALMAS DEL SOCORRO",
        "PALMIRA",
        "PALMITO",
        "PALOCABILDO",
        "PAMPLONA",
        "PAMPLONITA",
        "PANDI",
        "PANQUEBA",
        "PARAMO",
        "PARATEBUENO",
        "PASCA",
        "PASTO",
        "PATIA(EL BORDO)",
        "PAUNA",
        "PAYA",
        "PAZ DE ARIPORO",
        "PAZ DE RIO",
        "PEDRAZA",
        "PELAYA",
        "PENSILVANIA",
        "PEQUE",
        "PEREIRA",
        "PESCA",
        "PEÃ\x91OL",
        "PIAMONTE",
        "PIEDECUESTA",
        "PIEDRAS",
        "PIENDAMO",
        "PIJAO",
        "PIJIÃ\x91O DEL CARMEN",
        "PINCHOTE",
        "PINILLOS",
        "PIOJO",
        "PISVA",
        "PITAL",
        "PITALITO",
        "PIVIJAY",
        "PLANADAS",
        "PLANETA RICA",
        "PLATO",
        "POLICARPA",
        "POLONUEVO",
        "PONEDERA",
        "POPAYAN",
        "PORE",
        "POTOSI",
        "PRADERA",
        "PRADO",
        "PROVIDENCIA",
        "PTO SANTANDER",
        "PUEBLO BELLO",
        "PUEBLO NUEVO",
        "PUEBLO RICO",
        "PUEBLORRICO",
        "PUEBLOVIEJO",
        "PUENTE NACIONAL",
        "PUERRES",
        "PUERTO LEGUIZAMO",
        "PUERTO ASIS",
        "PUERTO BERRIO",
        "PUERTO BOYACA",
        "PUERTO CAICEDO",
        "PUERTO CARREÃ\x91O",
        "PUERTO COLOMBIA",
        "PUERTO CONCORDIA",
        "PUERTO ESCONDIDO",
        "PUERTO GAITAN",
        "PUERTO GUZMAN",
        "PUERTO LIBERTADOR",
        "PUERTO LLERAS",
        "PUERTO LOPEZ",
        "PUERTO NARE (LA MAGDALENA)",
        "PUERTO NARIÃ\x91O",
        "PUERTO PARRA",
        "PUERTO RICO",
        "PUERTO RONDON",
        "PUERTO SALGAR",
        "PUERTO SANTANDER",
        "PUERTO TEJADA",
        "PUERTO TRIUNFO",
        "PUERTO WILCHES",
        "PULI",
        "PUPIALES",
        "PURACE (COCONUCO)",
        "PURIFICACION",
        "PURISIMA",
        "QUEBRADANEGRA",
        "QUETAME",
        "QUIBDO",
        "QUIMBAYA",
        "QUINCHIA",
        "QUIPAMA",
        "QUIPILE",
        "RAFAEL REYES (APULO)",
        "RAGONVALIA",
        "RAMIRIQUI",
        "RAQUIRA",
        "RECETOR",
        "REGIDOR",
        "REMEDIOS",
        "REMOLINO",
        "REPELON",
        "RESTREPO",
        "RETIRO",
        "RICAURTE",
        "RIO DE ORO",
        "RIO IRO",
        "RIO QUITO",
        "RIO VIEJO",
        "RIOBLANCO",
        "RIOFRIO",
        "RIOHACHA",
        "RIONEGRO",
        "RIOSUCIO",
        "RISARALDA",
        "RIVERA",
        "ROBERTO PAYAN (SAN JOSE)",
        "ROLDANILLO",
        "RONCESVALLES",
        "RONDON",
        "ROSAS",
        "ROVIRA",
        "SABANA DE TORRES",
        "SABANAGRANDE",
        "SABANALARGA",
        "SABANAS DE SAN ANGEL",
        "SABANETA",
        "SABOYA",
        "SACAMA",
        "SACHICA",
        "SAHAGUN",
        "SALADOBLANCO",
        "SALAMINA",
        "SALAZAR",
        "SALDAÃ\x91A",
        "SALENTO",
        "SALGAR",
        "SAMACA",
        "SAMANA",
        "SAMANIEGO",
        "SAMPUES",
        "SAN AGUSTIN",
        "SAN ALBERTO",
        "SAN ANDRES",
        "SAN ANDRES SOTAVENTO",
        "SAN ANTERO",
        "SAN ANTONIO",
        "SAN ANTONIO DE TEQUENDAMA",
        "SAN BENITO",
        "SAN BENITO ABAD",
        "SAN BERNARDO",
        "SAN BERNARDO DEL VIENTO",
        "SAN CALIXTO",
        "SAN CARLOS",
        "SAN CARLOS DE GUAROA",
        "SAN CAYETANO",
        "SAN CRISTOBAL",
        "SAN DIEGO",
        "SAN EDUARDO",
        "SAN ESTANISLAO",
        "SAN FELIPE",
        "SAN FERNANDO",
        "SAN FRANCISCO",
        "SAN GIL",
        "SAN JACINTO",
        "SAN JACINTO DEL CAUCA",
        "SAN JERONIMO",
        "SAN JOAQUIN",
        "SAN JOSE",
        "SAN JOSE DE LA MONTAÃ\x91A",
        "SAN JOSE DE MIRANDA",
        "SAN JOSE DE PARE",
        "SAN JOSE DE URE",
        "SAN JOSE DEL FRAGUA",
        "SAN JOSE DEL GUAVIARE",
        "SAN JOSE DEL PALMAR",
        "SAN JUAN DE ARAMA",
        "SAN JUAN DE BETULIA",
        "SAN JUAN DE RIO SECO",
        "SAN JUAN DE URABA",
        "SAN JUAN DEL CESAR",
        "SAN JUAN NEPOMUCENO",
        "SAN JUANITO",
        "SAN LORENZO",
        "SAN LUIS",
        "SAN LUIS DE GACENO",
        "SAN LUIS DE PALENQUE",
        "SAN MARCOS",
        "SAN MARTIN",
        "SAN MARTIN DE LOBA",
        "SAN MATEO",
        "SAN MIGUEL",
        "SAN MIGUEL DE SEMA",
        "SAN ONOFRE",
        "SAN PABLO",
        "SAN PABLO DE BORBUR",
        "SAN PEDRO",
        "SAN PEDRO DE CARTAGO",
        "SAN PEDRO DE URABA",
        "SAN PELAYO",
        "SAN RAFAEL",
        "SAN ROQUE",
        "SAN SEBASTIAN",
        "SAN SEBASTIAN DE BUENAVISTA",
        "SAN VICENTE",
        "SAN VICENTE DE CHUCURI",
        "SAN VICENTE DEL CAGUAN",
        "SAN ZENON",
        "SANDONA",
        "SANTA ANA",
        "SANTA BARBARA",
        "SANTA BARBARA (ISCUANDE)",
        "SANTA BARBARA DE PINTO",
        "SANTA CATALINA",
        "SANTA HELENA DEL OPON",
        "SANTA ISABEL",
        "SANTA LUCIA",
        "SANTA MARIA",
        "SANTA MARTA",
        "SANTA ROSA",
        "SANTA ROSA DE CABAL",
        "SANTA ROSA DE OSOS",
        "SANTA ROSA DE VITERBO",
        "SANTA ROSA DEL SUR",
        "SANTA ROSALIA",
        "SANTA SOFIA",
        "SANTACRUZ (GUACHAVES)",
        "SANTAFÃ\x89 DE ANTIOQUIA",
        "SANTANA",
        "SANTANDER DE QUILICHAO",
        "SANTIAGO",
        "SANTO DOMINGO",
        "SANTO TOMAS",
        "SANTUARIO",
        "SAPUYES",
        "SARAVENA",
        "SARDINATA",
        "SASAIMA",
        "SATIVANORTE",
        "SATIVASUR",
        "SEGOVIA",
        "SESQUILE",
        "SEVILLA",
        "SIACHOQUE",
        "SIBATE",
        "SIBUNDOY",
        "SILOS",
        "SILVANIA",
        "SILVIA",
        "SIMACOTA",
        "SIMIJACA",
        "SIMITI",
        "SINCE",
        "SINCELEJO",
        "SIPI",
        "SITIONUEVO",
        "SOACHA",
        "SOATA",
        "SOCHA",
        "SOCORRO",
        "SOCOTA",
        "SOGAMOSO",
        "SOLANO",
        "SOLEDAD",
        "SOLITA",
        "SOMONDOCO",
        "SONSON",
        "SOPETRAN",
        "SOPLAVIENTO",
        "SOPO",
        "SORA",
        "SORACA",
        "SOTAQUIRA",
        "SOTARA (PAISPAMBA)",
        "SUAITA",
        "SUAN",
        "SUAREZ",
        "SUAZA",
        "SUBACHOQUE",
        "SUCRE",
        "SUESCA",
        "SUPATA",
        "SUPIA",
        "SURATA",
        "SUSA",
        "SUSACON",
        "SUTAMARCHAN",
        "SUTATAUSA",
        "SUTATENZA",
        "TABIO",
        "TADO",
        "TALAIGUA NUEVO",
        "TAMALAMEQUE",
        "TAMARA",
        "TAME",
        "TAMESIS",
        "TAMINANGO",
        "TANGUA",
        "TARAPACA",
        "TARAZA",
        "TARQUI",
        "TARSO",
        "TASCO",
        "TAURAMENA",
        "TAUSA",
        "TELLO",
        "TENA",
        "TENERIFE",
        "TENJO",
        "TENZA",
        "TEORAMA",
        "TERUEL",
        "TESALIA",
        "TIBACUY",
        "TIBANA",
        "TIBASOSA",
        "TIBIRITA",
        "TIBU",
        "TIERRALTA",
        "TIMANA",
        "TIMBIO",
        "TIMBIQUI",
        "TINJACA",
        "TIPACOQUE",
        "TIQUISIO (PUERTO RICO)",
        "TITIRIBI",
        "TOCA",
        "TOCAIMA",
        "TOCANCIPA",
        "TOGUI",
        "TOLEDO",
        "TOLU",
        "TOLUVIEJO",
        "TONA",
        "TOPAGA",
        "TOPAIPI",
        "TORIBIO",
        "TORO",
        "TOTA",
        "TOTORO",
        "TRINIDAD",
        "TRUJILLO",
        "TUBARA",
        "TUCHÃ\x8dN",
        "TULUA",
        "TUMACO",
        "TUNJA",
        "TUNUNGUA",
        "TUQUERRES",
        "TURBACO",
        "TURBANA",
        "TURBO",
        "TURMEQUE",
        "TUTA",
        "TUTASA",
        "UBALA",
        "UBAQUE",
        "UBATE",
        "ULLOA",
        "UMBITA",
        "UNE",
        "UNGUIA",
        "UNION PANAMERICANA",
        "URAMITA",
        "URIBIA",
        "URRAO",
        "URUMITA",
        "USIACURI",
        "UTICA",
        "VALDIVIA",
        "VALENCIA",
        "VALLE DE SAN JOSE",
        "VALLE DE SAN JUAN",
        "VALLEDUPAR",
        "VALPARAISO",
        "VEGACHI",
        "VELEZ",
        "VENADILLO",
        "VENECIA",
        "VENECIA (OSPINA PEREZ)",
        "VENTAQUEMADA",
        "VERGARA",
        "VERSALLES",
        "VETAS",
        "VIANI",
        "VICTORIA",
        "VIGIA DEL FUERTE",
        "VIJES",
        "VILLA CARO",
        "VILLA DE LEYVA",
        "VILLA DEL ROSARIO",
        "VILLA GUAMEZ (LA HORMIGA)",
        "VILLA RICA",
        "VILLAGARZON",
        "VILLAGOMEZ",
        "VILLAHERMOSA",
        "VILLAMARIA",
        "VILLANUEVA",
        "VILLAPINZON",
        "VILLARRICA",
        "VILLAVICENCIO",
        "VILLAVIEJA",
        "VILLETA",
        "VIOTA",
        "VIRACACHA",
        "VISTA HERMOSA",
        "VITERBO",
        "YACOPI",
        "YACUANQUER",
        "YAGUARA",
        "YALI",
        "YARUMAL",
        "YAVARATE",
        "YOLOMBO",
        "YONDO (CASABE)",
        "YOPAL",
        "YOTOCO",
        "YUMBO",
        "ZAMBRANO",
        "ZAPATOCA",
        "ZAPAYAN",
        "ZARAGOZA",
        "ZARZAL",
        "ZETAQUIRA",
        "ZIPACON",
        "ZIPAQUIRA",
        "ZONA BANANERA",
    ],
    "ESTU_MCPIO_RESIDE": [
        "ABEJORRAL",
        "ABRIAQUÃ\x8d",
        "ACACÃ\x8dAS",
        "ACANDÃ\x8d",
        "ACEVEDO",
        "ACHÃ\x8d",
        "AGRADO",
        "AGUA DE DIOS",
        "AGUACHICA",
        "AGUADA",
        "AGUADAS",
        "AGUAZUL",
        "AGUSTÃ\x8dN CODAZZI",
        "AIPE",
        "ALBANIA",
        "ALBÃ\x81N",
        "ALCALÃ\x81",
        "ALDANA",
        "ALEJANDRÃ\x8dA",
        "ALGARROBO",
        "ALGECIRAS",
        "ALMAGUER",
        "ALMEIDA",
        "ALPUJARRA",
        "ALTAMIRA",
        "ALTO BAUDÃ\x93",
        "ALTOS DEL ROSARIO",
        "ALVARADO",
        "AMAGÃ\x81",
        "AMALFI",
        "AMBALEMA",
        "ANAPOIMA",
        "ANCUYÃ\x81",
        "ANDALUCÃ\x8dA",
        "ANDES",
        "ANGELÃ\x93POLIS",
        "ANGOSTURA",
        "ANOLAIMA",
        "ANORÃ\x8d",
        "ANSERMA",
        "ANSERMANUEVO",
        "ANZOÃ\x81TEGUI",
        "ANZÃ\x81",
        "APARTADÃ\x93",
        "APULO",
        "APÃ\x8dA",
        "AQUITANIA",
        "ARACATACA",
        "ARANZAZU",
        "ARATOCA",
        "ARAUCA",
        "ARAUQUITA",
        "ARBELÃ\x81EZ",
        "ARBOLEDA",
        "ARBOLEDAS",
        "ARBOLETES",
        "ARCABUCO",
        "ARENAL",
        "ARGELIA",
        "ARIGUANÃ\x8d",
        "ARJONA",
        "ARMENIA",
        "ARMERO",
        "ARROYOHONDO",
        "ASTREA",
        "ATACO",
        "ATRATO",
        "AYAPEL",
        "BAGADÃ\x93",
        "BAHÃ\x8dA SOLANO",
        "BAJO BAUDÃ\x93",
        "BALBOA",
        "BARANOA",
        "BARAYA",
        "BARBACOAS",
        "BARBOSA",
        "BARICHARA",
        "BARRANCA DE UPÃ\x8dA",
        "BARRANCABERMEJA",
        "BARRANCAS",
        "BARRANCO DE LOBA",
        "BARRANCO MINAS",
        "BARRANQUILLA",
        "BECERRIL",
        "BELALCÃ\x81ZAR",
        "BELLO",
        "BELMIRA",
        "BELTRÃ\x81N",
        "BELÃ\x89N",
        "BELÃ\x89N DE BAJIRÃ\x81",
        "BELÃ\x89N DE LOS ANDAQUÃ\x8dES",
        "BELÃ\x89N DE UMBRÃ\x8dA",
        "BERBEO",
        "BETANIA",
        "BETULIA",
        "BETÃ\x89ITIVA",
        "BITUIMA",
        "BOAVITA",
        "BOCHALEMA",
        "BOGOTÃ\x81 D.C.",
        "BOJACÃ\x81",
        "BOJAYÃ\x81",
        "BOLÃ\x8dVAR",
        "BOSCONIA",
        "BOYACÃ\x81",
        "BRICEÃ\x91O",
        "BUCARAMANGA",
        "BUCARASICA",
        "BUENAVENTURA",
        "BUENAVISTA",
        "BUENOS AIRES",
        "BUESACO",
        "BUGALAGRANDE",
        "BURITICÃ\x81",
        "BUSBANZÃ\x81",
        "CABRERA",
        "CABUYARO",
        "CACHIPAY",
        "CAICEDO",
        "CAICEDONIA",
        "CAIMITO",
        "CAJAMARCA",
        "CAJIBÃ\x8dO",
        "CAJICÃ\x81",
        "CALAMAR",
        "CALARCÃ\x81",
        "CALDAS",
        "CALDONO",
        "CALI",
        "CALIFORNIA",
        "CALIMA",
        "CALOTO",
        "CAMPAMENTO",
        "CAMPO DE LA CRUZ",
        "CAMPOALEGRE",
        "CAMPOHERMOSO",
        "CANALETE",
        "CANDELARIA",
        "CANTAGALLO",
        "CAPARRAPÃ\x8d",
        "CAPITANEJO",
        "CARACOLÃ\x8d",
        "CARAMANTA",
        "CARCASÃ\x8d",
        "CAREPA",
        "CARMEN DE APICALÃ\x81",
        "CARMEN DE CARUPA",
        "CARMEN DEL DARIÃ\x89N",
        "CAROLINA",
        "CARTAGENA DE INDIAS",
        "CARTAGENA DEL CHAIRÃ\x81",
        "CARTAGO",
        "CARURÃ\x9a",
        "CASABIANCA",
        "CASTILLA LA NUEVA",
        "CAUCASIA",
        "CAÃ\x91ASGORDAS",
        "CEPITÃ\x81",
        "CERETÃ\x89",
        "CERINZA",
        "CERRITO",
        "CERRO DE SAN ANTONIO",
        "CHACHAGÃ\x9cÃ\x8d",
        "CHAGUANÃ\x8d",
        "CHALÃ\x81N",
        "CHAPARRAL",
        "CHARALÃ\x81",
        "CHARTA",
        "CHIGORODÃ\x93",
        "CHIMA",
        "CHIMICHAGUA",
        "CHIMÃ\x81",
        "CHINAVITA",
        "CHINCHINÃ\x81",
        "CHINÃ\x81COTA",
        "CHINÃ\x9a",
        "CHIPAQUE",
        "CHIPATÃ\x81",
        "CHIQUINQUIRÃ\x81",
        "CHIRIGUANÃ\x81",
        "CHISCAS",
        "CHITA",
        "CHITAGÃ\x81",
        "CHITARAQUE",
        "CHIVATÃ\x81",
        "CHIVOLO",
        "CHIVOR",
        "CHOACHÃ\x8d",
        "CHOCONTÃ\x81",
        "CHÃ\x81MEZA",
        "CHÃ\x8dA",
        "CHÃ\x8dQUIZA",
        "CICUCO",
        "CIMITARRA",
        "CIRCASIA",
        "CISNEROS",
        "CIUDAD BOLÃ\x8dVAR",
        "CIÃ\x89NAGA",
        "CIÃ\x89NAGA DE ORO",
        "CIÃ\x89NEGA",
        "CLEMENCIA",
        "COCORNÃ\x81",
        "COELLO",
        "COGUA",
        "COLOMBIA",
        "COLOSÃ\x93",
        "COLÃ\x93N",
        "CONCEPCIÃ\x93N",
        "CONCORDIA",
        "CONDOTO",
        "CONFINES",
        "CONSACÃ\x81",
        "CONTADERO",
        "CONTRATACIÃ\x93N",
        "CONVENCIÃ\x93N",
        "COPACABANA",
        "COPER",
        "CORINTO",
        "COROMORO",
        "COROZAL",
        "CORRALES",
        "COTA",
        "COTORRA",
        "COVARACHÃ\x8dA",
        "COVEÃ\x91AS",
        "COYAIMA",
        "CRAVO NORTE",
        "CUASPÃ\x9aD",
        "CUBARRAL",
        "CUBARÃ\x81",
        "CUCAITA",
        "CUCUNUBÃ\x81",
        "CUCUTILLA",
        "CUMARAL",
        "CUMARIBO",
        "CUMBAL",
        "CUMBITARA",
        "CUNDAY",
        "CURILLO",
        "CURITÃ\x8d",
        "CURUMANÃ\x8d",
        "CUÃ\x8dTIVA",
        "CÃ\x81CERES",
        "CÃ\x81CHIRA",
        "CÃ\x81COTA",
        "CÃ\x81QUEZA",
        "CÃ\x89RTEGUI",
        "CÃ\x93MBITA",
        "CÃ\x93RDOBA",
        "CÃ\x9aCUTA",
        "DABEIBA",
        "DAGUA",
        "DIBULLA",
        "DISTRACCIÃ\x93N",
        "DOLORES",
        "DONMATÃ\x8dAS",
        "DOSQUEBRADAS",
        "DUITAMA",
        "DURANIA",
        "EBÃ\x89JICO",
        "EL BAGRE",
        "EL BANCO",
        "EL CAIRO",
        "EL CALVARIO",
        "EL CANTÃ\x93N DEL SAN PABLO",
        "EL CARMEN",
        "EL CARMEN DE ATRATO",
        "EL CARMEN DE BOLÃ\x8dVAR",
        "EL CARMEN DE CHUCURÃ\x8d",
        "EL CARMEN DE VIBORAL",
        "EL CASTILLO",
        "EL CERRITO",
        "EL CHARCO",
        "EL COCUY",
        "EL COLEGIO",
        "EL COPEY",
        "EL DONCELLO",
        "EL DORADO",
        "EL DOVIO",
        "EL ENCANTO",
        "EL ESPINO",
        "EL GUACAMAYO",
        "EL GUAMO",
        "EL LITORAL DEL SAN JUAN",
        "EL MOLINO",
        "EL PASO",
        "EL PAUJÃ\x8dL",
        "EL PEÃ\x91OL",
        "EL PEÃ\x91Ã\x93N",
        "EL PIÃ\x91Ã\x93N",
        "EL PLAYÃ\x93N",
        "EL RETORNO",
        "EL RETÃ\x89N",
        "EL ROBLE",
        "EL ROSAL",
        "EL ROSARIO",
        "EL SANTUARIO",
        "EL TABLÃ\x93N DE GÃ\x93MEZ",
        "EL TAMBO",
        "EL TARRA",
        "EL ZULIA",
        "EL Ã\x81GUILA",
        "ELÃ\x8dAS",
        "ENCINO",
        "ENCISO",
        "ENTRERRÃ\x8dOS",
        "ENVIGADO",
        "ESPINAL",
        "EXTRANJERO",
        "F",
        "FACATATIVÃ\x81",
        "FALAN",
        "FILADELFIA",
        "FILANDIA",
        "FIRAVITOBA",
        "FLANDES",
        "FLORENCIA",
        "FLORESTA",
        "FLORIDA",
        "FLORIDABLANCA",
        "FLORIÃ\x81N",
        "FONSECA",
        "FORTUL",
        "FOSCA",
        "FRANCISCO PIZARRO",
        "FREDONIA",
        "FRESNO",
        "FRONTINO",
        "FUENTEDEORO",
        "FUNDACIÃ\x93N",
        "FUNES",
        "FUNZA",
        "FUSAGASUGÃ\x81",
        "FÃ\x93MEQUE",
        "FÃ\x9aQUENE",
        "GACHALÃ\x81",
        "GACHANCIPÃ\x81",
        "GACHANTIVÃ\x81",
        "GACHETÃ\x81",
        "GALAPA",
        "GALERAS",
        "GALÃ\x81N",
        "GAMA",
        "GAMARRA",
        "GARAGOA",
        "GARZÃ\x93N",
        "GIGANTE",
        "GINEBRA",
        "GIRALDO",
        "GIRARDOT",
        "GIRARDOTA",
        "GIRÃ\x93N",
        "GONZÃ\x81LEZ",
        "GRAMALOTE",
        "GRANADA",
        "GUACA",
        "GUACAMAYAS",
        "GUACARÃ\x8d",
        "GUACHENÃ\x89",
        "GUACHETÃ\x81",
        "GUACHUCAL",
        "GUADALAJARA DE BUGA",
        "GUADALUPE",
        "GUADUAS",
        "GUAITARILLA",
        "GUALMATÃ\x81N",
        "GUAMAL",
        "GUAMO",
        "GUAPOTÃ\x81",
        "GUAPÃ\x8d",
        "GUARANDA",
        "GUARNE",
        "GUASCA",
        "GUATAPÃ\x89",
        "GUATAQUÃ\x8d",
        "GUATAVITA",
        "GUATEQUE",
        "GUAVATÃ\x81",
        "GUAYABAL DE SÃ\x8dQUIMA",
        "GUAYABETAL",
        "GUAYATÃ\x81",
        "GUTIÃ\x89RREZ",
        "GUÃ\x81TICA",
        "GÃ\x81MBITA",
        "GÃ\x81MEZA",
        "GÃ\x89NOVA",
        "GÃ\x93MEZ PLATA",
        "GÃ\x9cEPSA",
        "GÃ\x9cICÃ\x81N DE LA SIERRA",
        "HACARÃ\x8d",
        "HATILLO DE LOBA",
        "HATO",
        "HATO COROZAL",
        "HATONUEVO",
        "HELICONIA",
        "HERRÃ\x81N",
        "HERVEO",
        "HISPANIA",
        "HOBO",
        "HONDA",
        "IBAGUÃ\x89",
        "ICONONZO",
        "ILES",
        "IMUÃ\x89S",
        "INZÃ\x81",
        "INÃ\x8dRIDA",
        "IPIALES",
        "ISNOS",
        "ISTMINA",
        "ITAGÃ\x9cÃ\x8d",
        "ITUANGO",
        "IZA",
        "JAMBALÃ\x93",
        "JAMUNDÃ\x8d",
        "JARDÃ\x8dN",
        "JENESANO",
        "JERICÃ\x93",
        "JERUSALÃ\x89N",
        "JESÃ\x9aS MARÃ\x8dA",
        "JORDÃ\x81N",
        "JUAN DE ACOSTA",
        "JUNÃ\x8dN",
        "JURADÃ\x93",
        "LA APARTADA",
        "LA ARGENTINA",
        "LA BELLEZA",
        "LA CALERA",
        "LA CAPILLA",
        "LA CEJA",
        "LA CELIA",
        "LA CHORRERA",
        "LA CRUZ",
        "LA CUMBRE",
        "LA DORADA",
        "LA ESPERANZA",
        "LA ESTRELLA",
        "LA FLORIDA",
        "LA GLORIA",
        "LA JAGUA DE IBIRICO",
        "LA JAGUA DEL PILAR",
        "LA LLANADA",
        "LA MACARENA",
        "LA MERCED",
        "LA MESA",
        "LA MONTAÃ\x91ITA",
        "LA PALMA",
        "LA PAZ",
        "LA PEDRERA",
        "LA PEÃ\x91A",
        "LA PINTADA",
        "LA PLATA",
        "LA PLAYA",
        "LA PRIMAVERA",
        "LA SALINA",
        "LA SIERRA",
        "LA TEBAIDA",
        "LA TOLA",
        "LA UNIÃ\x93N",
        "LA UVITA",
        "LA VEGA",
        "LA VICTORIA",
        "LA VIRGINIA",
        "LABATECA",
        "LABRANZAGRANDE",
        "LANDÃ\x81ZURI",
        "LEBRIJA",
        "LEIVA",
        "LEJANÃ\x8dAS",
        "LENGUAZAQUE",
        "LETICIA",
        "LIBORINA",
        "LINARES",
        "LLORÃ\x93",
        "LORICA",
        "LOS ANDES",
        "LOS CÃ\x93RDOBAS",
        "LOS PALMITOS",
        "LOS PATIOS",
        "LOS SANTOS",
        "LOURDES",
        "LURUACO",
        "LÃ\x89RIDA",
        "LÃ\x8dBANO",
        "LÃ\x93PEZ DE MICAY",
        "M",
        "MACANAL",
        "MACARAVITA",
        "MACEO",
        "MACHETÃ\x81",
        "MADRID",
        "MAGANGUÃ\x89",
        "MAGÃ\x9cÃ\x8d",
        "MAHATES",
        "MAICAO",
        "MAJAGUAL",
        "MALAMBO",
        "MALLAMA",
        "MANATÃ\x8d",
        "MANAURE",
        "MANAURE BALCÃ\x93N DEL CESAR",
        "MANIZALES",
        "MANTA",
        "MANZANARES",
        "MANÃ\x8d",
        "MAPIRIPANA",
        "MAPIRIPÃ\x81N",
        "MARGARITA",
        "MARINILLA",
        "MARIPÃ\x8d",
        "MARMATO",
        "MARQUETALIA",
        "MARSELLA",
        "MARULANDA",
        "MARÃ\x8dA LA BAJA",
        "MATANZA",
        "MEDELLÃ\x8dN",
        "MEDINA",
        "MEDIO ATRATO",
        "MEDIO BAUDÃ\x93",
        "MEDIO SAN JUAN",
        "MELGAR",
        "MERCADERES",
        "MESETAS",
        "MILÃ\x81N",
        "MIRAFLORES",
        "MIRANDA",
        "MIRITÃ\x8d - PARANÃ\x81",
        "MISTRATÃ\x93",
        "MITÃ\x9a",
        "MOCOA",
        "MOGOTES",
        "MOLAGAVITA",
        "MOMIL",
        "MOMPÃ\x93S",
        "MONGUA",
        "MONGUÃ\x8d",
        "MONIQUIRÃ\x81",
        "MONTEBELLO",
        "MONTECRISTO",
        "MONTELÃ\x8dBANO",
        "MONTENEGRO",
        "MONTERREY",
        "MONTERÃ\x8dA",
        "MORALES",
        "MORELIA",
        "MORROA",
        "MOSQUERA",
        "MOTAVITA",
        "MOÃ\x91ITOS",
        "MURILLO",
        "MURINDÃ\x93",
        "MUTATÃ\x81",
        "MUTISCUA",
        "MUZO",
        "MÃ\x81LAGA",
        "NARIÃ\x91O",
        "NATAGAIMA",
        "NECHÃ\x8d",
        "NECOCLÃ\x8d",
        "NEIRA",
        "NEIVA",
        "NEMOCÃ\x93N",
        "NILO",
        "NIMAIMA",
        "NOBSA",
        "NOCAIMA",
        "NORCASIA",
        "NOROSÃ\x8d",
        "NUEVA GRANADA",
        "NUEVO COLÃ\x93N",
        "NUNCHÃ\x8dA",
        "NUQUÃ\x8d",
        "NÃ\x81TAGA",
        "NÃ\x93VITA",
        "OBANDO",
        "OCAMONTE",
        "OCAÃ\x91A",
        "OIBA",
        "OICATÃ\x81",
        "OLAYA",
        "OLAYA HERRERA",
        "ONZAGA",
        "OPORAPA",
        "ORITO",
        "OROCUÃ\x89",
        "ORTEGA",
        "OSPINA",
        "OTANCHE",
        "OVEJAS",
        "PACHAVITA",
        "PACHO",
        "PADILLA",
        "PAICOL",
        "PAILITAS",
        "PAIME",
        "PAIPA",
        "PAJARITO",
        "PALERMO",
        "PALESTINA",
        "PALMAR",
        "PALMAR DE VARELA",
        "PALMAS DEL SOCORRO",
        "PALMIRA",
        "PALMITO",
        "PALOCABILDO",
        "PAMPLONA",
        "PAMPLONITA",
        "PANDI",
        "PANQUEBA",
        "PARATEBUENO",
        "PASCA",
        "PASTO",
        "PATÃ\x8dA",
        "PAUNA",
        "PAYA",
        "PAZ DE ARIPORO",
        "PAZ DE RÃ\x8dO",
        "PEDRAZA",
        "PELAYA",
        "PENSILVANIA",
        "PEQUE",
        "PEREIRA",
        "PESCA",
        "PEÃ\x91OL",
        "PIAMONTE",
        "PIEDECUESTA",
        "PIEDRAS",
        "PIENDAMÃ\x93 - TUNÃ\x8dA",
        "PIJAO",
        "PIJIÃ\x91O DEL CARMEN",
        "PINCHOTE",
        "PINILLOS",
        "PIOJÃ\x93",
        "PISBA",
        "PITAL",
        "PITALITO",
        "PIVIJAY",
        "PLANADAS",
        "PLANETA RICA",
        "PLATO",
        "POLICARPA",
        "POLONUEVO",
        "PONEDERA",
        "POPAYÃ\x81N",
        "PORE",
        "POTOSÃ\x8d",
        "PRADERA",
        "PRADO",
        "PROVIDENCIA",
        "PUEBLO BELLO",
        "PUEBLO NUEVO",
        "PUEBLO RICO",
        "PUEBLORRICO",
        "PUEBLOVIEJO",
        "PUENTE NACIONAL",
        "PUERRES",
        "PUERTO ASÃ\x8dS",
        "PUERTO BERRÃ\x8dO",
        "PUERTO BOYACÃ\x81",
        "PUERTO CAICEDO",
        "PUERTO CARREÃ\x91O",
        "PUERTO COLOMBIA",
        "PUERTO CONCORDIA",
        "PUERTO ESCONDIDO",
        "PUERTO GAITÃ\x81N",
        "PUERTO GUZMÃ\x81N",
        "PUERTO LEGUÃ\x8dZAMO",
        "PUERTO LIBERTADOR",
        "PUERTO LLERAS",
        "PUERTO LÃ\x93PEZ",
        "PUERTO NARE",
        "PUERTO NARIÃ\x91O",
        "PUERTO PARRA",
        "PUERTO RICO",
        "PUERTO RONDÃ\x93N",
        "PUERTO SALGAR",
        "PUERTO SANTANDER",
        "PUERTO TEJADA",
        "PUERTO TRIUNFO",
        "PUERTO WILCHES",
        "PULÃ\x8d",
        "PUPIALES",
        "PURACÃ\x89",
        "PURIFICACIÃ\x93N",
        "PURÃ\x8dSIMA DE LA CONCEPCIÃ\x93N",
        "PÃ\x81CORA",
        "PÃ\x81EZ",
        "PÃ\x81RAMO",
        "QUEBRADANEGRA",
        "QUETAME",
        "QUIBDÃ\x93",
        "QUIMBAYA",
        "QUINCHÃ\x8dA",
        "QUIPILE",
        "QUÃ\x8dPAMA",
        "RAGONVALIA",
        "RAMIRIQUÃ\x8d",
        "RECETOR",
        "REGIDOR",
        "REMEDIOS",
        "REMOLINO",
        "REPELÃ\x93N",
        "RESTREPO",
        "RETIRO",
        "RICAURTE",
        "RIOBLANCO",
        "RIOFRÃ\x8dO",
        "RIOHACHA",
        "RIONEGRO",
        "RIOSUCIO",
        "RISARALDA",
        "RIVERA",
        "ROBERTO PAYÃ\x81N",
        "ROLDANILLO",
        "RONCESVALLES",
        "RONDÃ\x93N",
        "ROSAS",
        "ROVIRA",
        "RÃ\x81QUIRA",
        "RÃ\x8dO DE ORO",
        "RÃ\x8dO IRÃ\x93",
        "RÃ\x8dO QUITO",
        "RÃ\x8dO VIEJO",
        "SABANA DE TORRES",
        "SABANAGRANDE",
        "SABANALARGA",
        "SABANAS DE SAN Ã\x81NGEL",
        "SABANETA",
        "SABOYÃ\x81",
        "SAHAGÃ\x9aN",
        "SALADOBLANCO",
        "SALAMINA",
        "SALAZAR",
        "SALDAÃ\x91A",
        "SALENTO",
        "SALGAR",
        "SAMACÃ\x81",
        "SAMANIEGO",
        "SAMANÃ\x81",
        "SAMPUÃ\x89S",
        "SAN AGUSTÃ\x8dN",
        "SAN ALBERTO",
        "SAN ANDRÃ\x89S",
        "SAN ANDRÃ\x89S DE CUERQUÃ\x8dA",
        "SAN ANDRÃ\x89S DE SOTAVENTO",
        "SAN ANDRÃ\x89S DE TUMACO",
        "SAN ANTERO",
        "SAN ANTONIO",
        "SAN ANTONIO DEL TEQUENDAMA",
        "SAN BENITO",
        "SAN BENITO ABAD",
        "SAN BERNARDO",
        "SAN BERNARDO DEL VIENTO",
        "SAN CALIXTO",
        "SAN CARLOS",
        "SAN CARLOS DE GUAROA",
        "SAN CAYETANO",
        "SAN CRISTÃ\x93BAL",
        "SAN DIEGO",
        "SAN EDUARDO",
        "SAN ESTANISLAO",
        "SAN FELIPE",
        "SAN FERNANDO",
        "SAN FRANCISCO",
        "SAN GIL",
        "SAN JACINTO",
        "SAN JACINTO DEL CAUCA",
        "SAN JERÃ\x93NIMO",
        "SAN JOAQUÃ\x8dN",
        "SAN JOSÃ\x89",
        "SAN JOSÃ\x89 DE LA MONTAÃ\x91A",
        "SAN JOSÃ\x89 DE MIRANDA",
        "SAN JOSÃ\x89 DE PARE",
        "SAN JOSÃ\x89 DE URÃ\x89",
        "SAN JOSÃ\x89 DEL FRAGUA",
        "SAN JOSÃ\x89 DEL GUAVIARE",
        "SAN JOSÃ\x89 DEL PALMAR",
        "SAN JUAN DE ARAMA",
        "SAN JUAN DE BETULIA",
        "SAN JUAN DE RIOSECO",
        "SAN JUAN DE URABÃ\x81",
        "SAN JUAN DEL CESAR",
        "SAN JUAN NEPOMUCENO",
        "SAN JUANITO",
        "SAN LORENZO",
        "SAN LUIS",
        "SAN LUIS DE GACENO",
        "SAN LUIS DE PALENQUE",
        "SAN LUIS DE SINCÃ\x89",
        "SAN MARCOS",
        "SAN MARTÃ\x8dN",
        "SAN MARTÃ\x8dN DE LOBA",
        "SAN MATEO",
        "SAN MIGUEL",
        "SAN MIGUEL DE SEMA",
        "SAN ONOFRE",
        "SAN PABLO",
        "SAN PABLO DE BORBUR",
        "SAN PEDRO",
        "SAN PEDRO DE CARTAGO",
        "SAN PEDRO DE LOS MILAGROS",
        "SAN PEDRO DE URABÃ\x81",
        "SAN PELAYO",
        "SAN RAFAEL",
        "SAN ROQUE",
        "SAN SEBASTIÃ\x81N",
        "SAN SEBASTIÃ\x81N DE BUENAVISTA",
        "SAN SEBASTIÃ\x81N DE MARIQUITA",
        "SAN VICENTE DE CHUCURÃ\x8d",
        "SAN VICENTE DEL CAGUÃ\x81N",
        "SAN VICENTE FERRER",
        "SAN ZENÃ\x93N",
        "SANDONÃ\x81",
        "SANTA ANA",
        "SANTA BÃ\x81RBARA",
        "SANTA BÃ\x81RBARA DE PINTO",
        "SANTA CATALINA",
        "SANTA FÃ\x89 DE ANTIOQUIA",
        "SANTA HELENA DEL OPÃ\x93N",
        "SANTA ISABEL",
        "SANTA LUCÃ\x8dA",
        "SANTA MARTA",
        "SANTA MARÃ\x8dA",
        "SANTA ROSA",
        "SANTA ROSA DE CABAL",
        "SANTA ROSA DE OSOS",
        "SANTA ROSA DE VITERBO",
        "SANTA ROSA DEL SUR",
        "SANTA ROSALÃ\x8dA",
        "SANTA SOFÃ\x8dA",
        "SANTACRUZ",
        "SANTANA",
        "SANTANDER DE QUILICHAO",
        "SANTIAGO",
        "SANTIAGO DE TOLÃ\x9a",
        "SANTO DOMINGO",
        "SANTO TOMÃ\x81S",
        "SANTUARIO",
        "SAPUYES",
        "SARAVENA",
        "SARDINATA",
        "SASAIMA",
        "SATIVANORTE",
        "SATIVASUR",
        "SEGOVIA",
        "SESQUILÃ\x89",
        "SEVILLA",
        "SIACHOQUE",
        "SIBATÃ\x89",
        "SIBUNDOY",
        "SILOS",
        "SILVANIA",
        "SILVIA",
        "SIMACOTA",
        "SIMIJACA",
        "SIMITÃ\x8d",
        "SINCELEJO",
        "SIPÃ\x8d",
        "SITIONUEVO",
        "SOACHA",
        "SOATÃ\x81",
        "SOCHA",
        "SOCORRO",
        "SOCOTÃ\x81",
        "SOGAMOSO",
        "SOLANO",
        "SOLEDAD",
        "SOLITA",
        "SOMONDOCO",
        "SONSÃ\x93N",
        "SOPETRÃ\x81N",
        "SOPLAVIENTO",
        "SOPÃ\x93",
        "SORA",
        "SORACÃ\x81",
        "SOTAQUIRÃ\x81",
        "SOTARA",
        "SUAITA",
        "SUAN",
        "SUAZA",
        "SUBACHOQUE",
        "SUCRE",
        "SUESCA",
        "SUPATÃ\x81",
        "SUPÃ\x8dA",
        "SURATÃ\x81",
        "SUSA",
        "SUSACÃ\x93N",
        "SUTAMARCHÃ\x81N",
        "SUTATAUSA",
        "SUTATENZA",
        "SUÃ\x81REZ",
        "SÃ\x81CAMA",
        "SÃ\x81CHICA",
        "TABIO",
        "TADÃ\x93",
        "TALAIGUA NUEVO",
        "TAMALAMEQUE",
        "TAME",
        "TAMINANGO",
        "TANGUA",
        "TARAIRA",
        "TARAPACÃ\x81",
        "TARAZÃ\x81",
        "TARQUI",
        "TARSO",
        "TASCO",
        "TAURAMENA",
        "TAUSA",
        "TELLO",
        "TENA",
        "TENERIFE",
        "TENJO",
        "TENZA",
        "TEORAMA",
        "TERUEL",
        "TESALIA",
        "TIBACUY",
        "TIBANÃ\x81",
        "TIBASOSA",
        "TIBIRITA",
        "TIBÃ\x9a",
        "TIERRALTA",
        "TIMANÃ\x81",
        "TIMBIQUÃ\x8d",
        "TIMBÃ\x8dO",
        "TINJACÃ\x81",
        "TIPACOQUE",
        "TIQUISIO",
        "TITIRIBÃ\x8d",
        "TOCA",
        "TOCAIMA",
        "TOCANCIPÃ\x81",
        "TOGÃ\x9cÃ\x8d",
        "TOLEDO",
        "TOLÃ\x9a VIEJO",
        "TONA",
        "TOPAIPÃ\x8d",
        "TORIBÃ\x8dO",
        "TORO",
        "TOTA",
        "TOTORÃ\x93",
        "TRINIDAD",
        "TRUJILLO",
        "TUBARÃ\x81",
        "TUCHÃ\x8dN",
        "TULUÃ\x81",
        "TUNJA",
        "TUNUNGUÃ\x81",
        "TURBACO",
        "TURBANÃ\x81",
        "TURBO",
        "TURMEQUÃ\x89",
        "TUTA",
        "TUTAZÃ\x81",
        "TÃ\x81MARA",
        "TÃ\x81MESIS",
        "TÃ\x93PAGA",
        "TÃ\x9aQUERRES",
        "UBALÃ\x81",
        "UBAQUE",
        "ULLOA",
        "UNE",
        "UNGUÃ\x8dA",
        "UNIÃ\x93N PANAMERICANA",
        "URAMITA",
        "URIBE",
        "URIBIA",
        "URRAO",
        "URUMITA",
        "USIACURÃ\x8d",
        "VALDIVIA",
        "VALENCIA",
        "VALLE DE SAN JOSÃ\x89",
        "VALLE DE SAN JUAN",
        "VALLE DEL GUAMUEZ",
        "VALLEDUPAR",
        "VALPARAÃ\x8dSO",
        "VEGACHÃ\x8d",
        "VENADILLO",
        "VENECIA",
        "VENTAQUEMADA",
        "VERGARA",
        "VERSALLES",
        "VETAS",
        "VIANÃ\x8d",
        "VICTORIA",
        "VIGÃ\x8dA DEL FUERTE",
        "VIJES",
        "VILLA CARO",
        "VILLA DE LEYVA",
        "VILLA DE SAN DIEGO DE UBATÃ\x89",
        "VILLA DEL ROSARIO",
        "VILLA RICA",
        "VILLAGARZÃ\x93N",
        "VILLAGÃ\x93MEZ",
        "VILLAHERMOSA",
        "VILLAMARÃ\x8dA",
        "VILLANUEVA",
        "VILLAPINZÃ\x93N",
        "VILLARRICA",
        "VILLAVICENCIO",
        "VILLAVIEJA",
        "VILLETA",
        "VIOTÃ\x81",
        "VIRACACHÃ\x81",
        "VISTAHERMOSA",
        "VITERBO",
        "VÃ\x89LEZ",
        "YACOPÃ\x8d",
        "YACUANQUER",
        "YAGUARÃ\x81",
        "YALÃ\x8d",
        "YARUMAL",
        "YAVARATÃ\x89",
        "YOLOMBÃ\x93",
        "YONDÃ\x93",
        "YOPAL",
        "YOTOCO",
        "YUMBO",
        "ZAMBRANO",
        "ZAPATOCA",
        "ZAPAYÃ\x81N",
        "ZARAGOZA",
        "ZARZAL",
        "ZETAQUIRA",
        "ZIPACÃ\x93N",
        "ZIPAQUIRÃ\x81",
        "ZONA BANANERA",
        "unknown",
        "Ã\x81BREGO",
        "Ã\x8dQUIRA",
        "Ã\x9aMBITA",
        "Ã\x9aTICA",
    ],
    "FAMI_CUARTOSHOGAR": [
        "Cinco",
        "Cuatro",
        "Diez o mÃ¡s",
        "Dos",
        "Nueve",
        "Ocho",
        "Seis",
        "Siete",
        "Tres",
        "Uno",
    ],
}

columnas_modelo = [
    "COLE_AREA_UBICACION",
    "COLE_BILINGUE",
    "COLE_CARACTER",
    "COLE_GENERO",
    "COLE_MCPIO_UBICACION",
    "COLE_NATURALEZA",
    "COLE_SEDE_PRINCIPAL",
    "ESTU_GENERO",
    "ESTU_MCPIO_RESIDE",
    "FAMI_CUARTOSHOGAR",
    "FAMI_EDUCACIONMADRE",
    "FAMI_EDUCACIONPADRE",
    "FAMI_ESTRATOVIVIENDA",
    "FAMI_PERSONASHOGAR",
    "FAMI_TIENEAUTOMOVIL",
    "FAMI_TIENECOMPUTADOR",
]

# Crear app Dash
app = dash.Dash(__name__)
app.title = "Clasificación Saber11"

# Layout principal
# Layout principal
app.layout = html.Div(
    style={"backgroundColor": "#FFF8E1", "padding": "20px"},
    children=[
        html.Img(
            src="/assets/fotoUniandes.png",
            style={
                "height": "200px",
                "marginRight": "20px",
                "objectFit": "contain",
                "width": "auto",
            },
        ),
        html.H1(
            "Predicción de Alto Desempeño - Saber11", style={"textAlign": "center"}
        ),
        html.Hr(),
        # Gráfica Comparativa
        html.H2(
            "Comparación de Educación de Padres con PUNT_GLOBAL",
            style={"textAlign": "center"},
        ),
        html.Label("Selecciona una variable:"),
        dcc.Dropdown(
            id="dropdown-variable-principal",
            options=opciones_educacion,
            placeholder="Selecciona Educación de la Madre o del Padre",
        ),
        dcc.Graph(id="grafica-principal"),
        # Análisis Exploratorio
        html.H2("Análisis Exploratorio Libre", style={"textAlign": "center"}),
        html.Label("Selecciona una variable para el eje X:"),
        dcc.Dropdown(
            id="dropdown-x-variable",
            options=[{"label": col, "value": col} for col in df.columns],
            placeholder="Selecciona variable para el eje X",
        ),
        html.Label("Selecciona una variable para el eje Y:"),
        dcc.Dropdown(
            id="dropdown-y-variable",
            options=[{"label": col, "value": col} for col in df.columns],
            placeholder="Selecciona variable para el eje Y",
        ),
        dcc.Graph(id="grafica-libre"),
        html.Hr(),
        html.H2("Predicción Personalizada", style={"textAlign": "center"}),
        html.Div(
            style={"display": "flex", "gap": "40px"},
            children=[
                #  Columna izquierda: formulario
                html.Div(
                    style={
                        "flex": "1",
                        "backgroundColor": "#F9FAFB",
                        "padding": "20px",
                        "borderRadius": "10px",
                        "boxShadow": "0 2px 8px rgba(0,0,0,0.05)",
                    },
                    children=[
                        html.H3("Completa la información del estudiante"),
                        html.Div(
                            [
                                html.Div(
                                    [
                                        html.Label(col, style={"fontWeight": "bold"}),
                                        (
                                            dcc.Dropdown(
                                                id=col,
                                                options=[
                                                    {"label": str(opt), "value": opt}
                                                    for opt in opciones.get(col, [])
                                                ],
                                                placeholder=f"Selecciona {col}",
                                            )
                                            if col in opciones
                                            else dcc.Input(
                                                id=col,
                                                type="number",
                                                placeholder=f"Ingrese {col}",
                                                required=True,
                                            )
                                        ),
                                    ],
                                    style={"marginBottom": "10px"},
                                )
                                for col in columnas_modelo
                            ]
                        ),
                        html.Button("Predecir", id="submit-button", n_clicks=0),
                        html.Br(),
                        html.Br(),
                        html.Div(
                            id="resultado-prediccion",
                            style={"fontSize": "22px", "color": "#0033A0"},
                        ),
                    ],
                ),
                #  Columna derecha: descripción del sistema
                html.Div(
                    style={
                        "flex": "1",
                        "backgroundColor": "#FFF9C4",  # Amarillo Uniandes claro
                        "padding": "30px",
                        "borderRadius": "10px",
                        "boxShadow": "0 2px 8px rgba(0,0,0,0.08)",
                    },
                    children=[
                        html.H2(
                            " ¿Qué busca esta herramienta?",
                            style={"color": "#0033A0"},
                        ),
                        html.P(
                            "Esta herramienta busca responder a la pregunta:",
                            style={"fontSize": "16px", "marginTop": "10px"},
                        ),
                        html.Blockquote(
                            "¿Qué características del entorno familiar y del colegio están más asociadas con un desempeño que le permita al estudiante ingresar a la Universidad de los Andes?",
                            style={
                                "fontSize": "15px",
                                "fontStyle": "italic",
                                "color": "#333",
                                "marginBottom": "20px",
                                "borderLeft": "4px solid #0033A0",
                                "paddingLeft": "12px",
                            },
                        ),
                        html.P(
                            "Solución predictiva:",
                            style={
                                "fontWeight": "bold",
                                "fontSize": "16px",
                                "marginBottom": "5px",
                            },
                        ),
                        html.P(
                            "A partir de un modelo de clasificación basado en variables socio-demográficas del estudiante —como el tipo de colegio, el nivel educativo de los padres, el género, entre otros—, esta solución busca identificar perfiles con alto potencial de ingreso a la Universidad de los Andes.",
                            style={"fontSize": "15px"},
                        ),
                        html.P(
                            "El modelo analiza las probabilidades de ingreso considerando únicamente las siguientes carreras universitarias:",
                            style={"fontSize": "15px", "marginTop": "15px"},
                        ),
                        html.Ul(
                            [
                                html.Li(carrera, style={"marginBottom": "4px"})
                                for carrera in [
                                    "Administración",
                                    "Biología",
                                    "Física",
                                    "Geociencias",
                                    "Matemáticas",
                                    "Química",
                                    "Economía",
                                    "Ingeniería Ambiental",
                                    "Ingeniería Civil",
                                    "Ingeniería Biomédica",
                                    "Ingeniería de Sistemas y Computación",
                                    "Ingeniería Electrónica",
                                    "Ingeniería Industrial",
                                    "Ingeniería Mecánica",
                                    "Ingeniería Química",
                                ]
                            ],
                            style={
                                "columns": 2,
                                "fontSize": "14px",
                                "marginBottom": "15px",
                            },
                        ),
                    ],
                ),
            ],
        ),
        # Gráfico de carreras (opcional después de predicción)
        html.Br(),
        html.Div(id="vista-predictiva", style={"marginTop": "20px"}),
        dcc.Graph(id="grafica-carreras", style={"display": "none"}),
    ],
)


@app.callback(
    [
        Output("resultado-prediccion", "children"),
        Output("vista-predictiva", "children"),
        Output("grafica-carreras", "figure"),
        Output("grafica-carreras", "style"),
    ],
    Input("submit-button", "n_clicks"),
    [State(col, "value") for col in columnas_modelo],
)
def predecir(n_clicks, *valores):
    if n_clicks > 0:
        if None in valores:
            return (
                "Por favor ingresa todos los valores.",
                "",
                {},
                {"display": "none"},
            )

        X_nuevo = pd.DataFrame([valores], columns=columnas_modelo)

        normalizaciones = {
            "TÉCNICO": "TÃ\x89CNICO",
            "TÉCNICO/ACADÉMICO": "TÃ\x89CNICO/ACADÃ\x89MICO",
            "ACADÉMICO": "ACADÃ\x89MICO",
            "OTRO": "unknown",
            "NO OFICIAL": "NO OFICIAL",
            "OFICIAL": "OFICIAL",
            "SÍ": "S",
            "SI": "S",
            "NO": "N",
            "S": "S",
            "MIXTO": "MIXTO",
            "ESTRATO 1": "Estrato 1",
            "ESTRATO 2": "Estrato 2",
            "ESTRATO 3": "Estrato 3",
            "ESTRATO 4": "Estrato 4",
            "ESTRATO 5": "Estrato 5",
            "ESTRATO 6": "Estrato 6",
            "1": "Una",
            "2": "Dos",
            "3": "Tres",
            "4": "Cuatro",
            "5": "Cinco",
            "6": "Seis",
            "7": "Siete",
            "8": "Ocho",
            "9": "Nueve",
            "10": "Diez",
            "11": "Once",
            "12": "Doce o más",
        }

        exclusiones_upper = {
            "FAMI_ESTRATOVIVIENDA",
            "FAMI_CUARTOSHOGAR",
            "FAMI_PERSONASHOGAR",
            "FAMI_EDUCACIONMADRE",
            "FAMI_EDUCACIONPADRE",
            "FAMI_TIENEAUTOMOVIL",
            "FAMI_TIENECOMPUTADOR",
        }

        for col in columnas_modelo:
            if col in X_nuevo.columns:
                valor = str(X_nuevo.at[0, col]).strip()
                if col not in exclusiones_upper:
                    valor = valor.upper()
                X_nuevo.at[0, col] = normalizaciones.get(valor, valor)

        for col in columnas_modelo:
            if col in encoders:
                le = encoders[col]
                try:
                    X_nuevo[col] = le.transform([X_nuevo.at[0, col]])
                except ValueError:
                    valores_validos = list(le.classes_)
                    return (
                        f" Valor inválido para '{col}': '{X_nuevo.at[0, col]}'. Valores válidos: {valores_validos}",
                        "",
                        {},
                        {"display": "none"},
                    )

        try:
            X_nuevo = X_nuevo.astype("float32")
        except:
            return (
                " Error al convertir los datos a formato numérico.",
                "",
                {},
                {"display": "none"},
            )

        prediccion = model.predict(X_nuevo)[0][0]
        mensaje = (
            f"Predicción: Alto Desempeño ({prediccion:.2%})"
            if prediccion >= 0.4
            else f" Predicción: No Alto Desempeño ({prediccion:.2%})"
        )

        if prediccion >= 0.4:
            vista = html.Div(
                [
                    html.P(
                        " En promedio estás encima de 310. ¡Puedes aplicar a las siguientes carreras!",
                        style={
                            "marginBottom": "10px",
                            "fontSize": "18px",
                        },
                    ),
                    html.A(
                        "Dirígete al sitio de admisiones de Uniandes",
                        href="https://www.uniandes.edu.co/",
                        target="_blank",
                        style={
                            "color": "#0033A0",
                            "fontWeight": "bold",
                            "marginBottom": "20px",
                            "display": "inline-block",
                            "fontSize": "18px",
                        },
                    ),
                    html.Div(
                        [
                            html.Div(
                                [
                                    html.Div(
                                        carrera,
                                        style={
                                            "padding": "15px",
                                            "backgroundColor": "#f0f0f0",
                                            "border": "1px solid #ccc",
                                            "width": "80%",
                                            "fontWeight": "bold",
                                            "fontSize": "16px",
                                        },
                                    ),
                                    html.Div(
                                        "310",
                                        style={
                                            "padding": "15px",
                                            "backgroundColor": "#FFD700",
                                            "border": "1px solid #ccc",
                                            "width": "20%",
                                            "textAlign": "center",
                                            "fontWeight": "bold",
                                            "fontSize": "16px",
                                        },
                                    ),
                                ],
                                style={
                                    "display": "flex",
                                    "flexDirection": "row",
                                    "marginBottom": "5px",
                                    "boxShadow": "0 1px 3px rgba(0,0,0,0.1)",
                                },
                            )
                            for carrera in [
                                "Administración",
                                "Biología",
                                "Física",
                                "Geociencias",
                                "Matemáticas",
                                "Química",
                                "Economía",
                                "Ingeniería Ambiental",
                                "Ingeniería Civil",
                                "Ingeniería Biomédica",
                                "Ingeniería de Sistemas y Computación",
                                "Ingeniería Electrónica",
                            ]
                        ],
                        style={
                            "backgroundColor": "#FFFFFF",
                            "padding": "10px",
                            "borderRadius": "8px",
                            "border": "1px solid #ddd",
                            "marginTop": "20px",
                        },
                    ),
                ]
            )

            return mensaje, vista, {}, {"display": "none"}
        else:
            vista = html.Div(
                "⏳ Está por verse... sigue preparándote para mejorar tu puntaje."
            )
            return mensaje, vista, {}, {"display": "none"}

    return "", "", {}, {"display": "none"}


# Callback para el gráfico principal (Educación Padres)
@app.callback(
    Output("grafica-principal", "figure"), Input("dropdown-variable-principal", "value")
)
def actualizar_grafica_principal(variable):
    if variable is None:
        return {}
    fig = px.box(
        df,
        x=variable,
        y="PUNT_GLOBAL",
        color=variable,
        title=f"Distribución de PUNT_GLOBAL por {variable}",
    )
    fig.update_layout(transition_duration=500)
    return fig


# Callback para el gráfico libre
@app.callback(
    Output("grafica-libre", "figure"),
    [Input("dropdown-x-variable", "value"), Input("dropdown-y-variable", "value")],
)
def actualizar_grafica_libre(x_var, y_var):
    if x_var is None or y_var is None:
        return {}
    fig = px.scatter(df, x=x_var, y=y_var, color=x_var, title=f"{y_var} vs {x_var}")
    fig.update_layout(transition_duration=500)
    return fig


if __name__ == "__main__":
    app.run(debug=True)
